export {default as ExercisesPage} from './exercisesPage'
export {default as NewExercisePage} from './newExercisePage'
export {default as ExercisePage} from './exercisePage'
export {default as ExercisesList} from './exercisesList'
export {default as ExerciseForm} from './exerciseForm'