export {default as WorkoutsPage} from './workoutsPage'
export {default as NewWorkoutPage} from './newWorkoutPage'
export {default as WorkoutPage} from './workoutPage'
export {default as WorkoutsList} from './workoutsList'
export {default as WorkoutForm} from './workoutForm'